### ISSUE TITLE
Changes on github not being pushed to website

### ISSUE THREAD

**Issue by jack-cole** [CCSF-Coders/ccsf_coders_website#37]
I've updated the page on github, but it doesn't appear to be applying to the website.

**Comment by possibly** [comment]
Hey @jack-cole ! I am a past Coders Club president and have worked extensively on the website.

You will need to ssh into the webserver and manually pull the changes onto the webserver. We have attempted to setup an automated process whereby pushing a change to the master branch would automatically pull the changes to the webserver. However, I think the issue was that the webserver was too secure to allow that type of automation.

**Comment by jack-cole** [comment]
Alright, thanks. I'm seeing if I can get the coders login information. I work at the ACRC so they could just reset the login and pw for me too.

Maybe it can be automated using a key file. I've seen instructors automated their login to hills using key files.

**Comment by akmartinez1** [comment]
If you get the password reset in any way you need to let the leaders know.  I and a few others have access to the account and if it gets changed we need to know.

**Comment by jack-cole** [comment]
I'm talking with the current club leaders, and none of them know. If you know the password or how to get it, are you able contact Ryan? He's the current leader.

**Comment by kmolo** [comment]
Sorry for being MIA on this conversation.  I just tried the latest hills password I had for this account, and it worked (and it also made me change the password).  I'm emailing everyone to set up a time to pass along the new password.

In the meantime, I pulled the changes to website over into the live site.
